### PR TITLE
Don't search /dev for disks by default

### PR DESCRIPTION
**Pull request by ghost**
When no search path is specified, libzfs iterates through geom
providers. Do this by default.

### CODE REVIEW

**Comment by sonicaj** [comment]
@freqlabs how does zol do this ? Do we need to define a search path for zol in middleware ?

**Review by william-gr — APPROVED** [review]

**Comment by ghost** [comment]
@sonicaj This change will cause the search to use libblkid on Linux and geom on FreeBSD. On both platforms libzfs will search all the specified paths if given, or a default set of paths if the search arg is true (I mentioned the importargs_t mismatch in Ryver). When paths == 0 and search == false the blkid/geom behavior is invoked.

We currently do not filter out devices that should not be opened (such as ttyu*), so the search method invoked by specifying "/dev" as a path was getting hung up when it encountered /dev/ttyu1. I will probably add this eventually, but I don't think it should cause any issues in most situations after the change in this PR is incorporated.

**Comment by sonicaj** [comment]
Thank you for elaborating @freqlabs

**Comment by william-gr** [comment]
@sonicaj do you mind updating the port for us, please?

**Pull request merged**
