### PR TITLE
Free up nvlist objects where necessary

### LINKED ISSUE #155: Memory leak
The following small python code leaks memory:
```
import libzfs
with libzfs.ZFS() as zfs:
  for event in zfs.zpool_events(blocking=True, skip_existing_events=True):
    pass
```
In parallell you should generate zfs events (e.g. create/destroy datasets, etc.). Then memory usage will increase.

### PR DESCRIPTION
**Pull request by rkojedzinszky**
Fixes #155

### CODE REVIEW

**Comment by rkojedzinszky** [comment]
I've updated to a more readable fix

**Review by sonicaj — COMMENTED** [review]
Thank you for your contribution @rkojedzinszky. Do you think the changes you introduced before are better wrt cleaning up the nvlist automatically in NVlist class ? ( i think that might be better instead of us doing it in lots of different places )

**Comment by rkojedzinszky** [comment]
> Thank you for your contribution @rkojedzinszky. Do you think the changes you introduced before are better wrt cleaning up the nvlist automatically in NVlist class ? ( i think that might be better instead of us doing it in lots of different places )

In some places, libzfs returns nvlists which must be freed by the caller, and in some cases, libzfs will free it. So, if we want this task be handled by NVList, then NVList must know if it must do the free. I've searched libzfs.pyx for nvlist C structures, and found those places only where nvlist structures must be freed by us. Maybe I've missed some other occurences, then those will need to be handled as well. 

My first push https://github.com/truenas/py-libzfs/commit/4129767092c2593390639f78ca0c64fd28cdcfd3 introduced a new arg to NVList, but that diff is larger with NVList modifications, and we also need to instantiate NVList in the few cases in a different way.

I am running my truenas box with these changes, and a memory leak has disappeared in one of the python processes (zfs event daemon), and there are no segfaults.

**Comment by rkojedzinszky** [comment]
> > Thank you for your contribution @rkojedzinszky. Do you think the changes you introduced before are better wrt cleaning up the nvlist automatically in NVlist class ? ( i think that might be better instead of us doing it in lots of different places )
> 
> In some places, libzfs returns nvlists which must be freed by the caller, and in some cases, libzfs will free it. So, if we want this task be handled by NVList, then NVList must know if it must do the free. I've searched libzfs.pyx for nvlist C structures, and found those places only where nvlist structures must be freed by us. Maybe I've missed some other occurences, then those will need to be handled as well.
> 
> My first push [4129767](https://github.com/truenas/py-libzfs/commit/4129767092c2593390639f78ca0c64fd28cdcfd3) introduced a new arg to NVList, but that diff is larger with NVList modifications, and we also need to instantiate NVList in the few cases in a different way.

So, I prefer the latest solution. It does not change NVList semantics, and in the few places it is clear that nvlist structures are being released. Also, in `__deallocate__` there is no additional `if` statement, thus no little performance overhead introduced even. :)

> 
> I am running my truenas box with these changes, and a memory leak has disappeared in one of the python processes (zfs event daemon), and there are no segfaults.

**Review by sonicaj — APPROVED** [review]
Great, thanks for the changes! ( i can revisit these if i found more usages and do some refactoring in that case )

**Pull request merged**
