### PR TITLE
NAS-117039 / 22.12 / Properly handle `ZPOOL_STATUS_INCOMPATIBLE_FEAT`

### PR DESCRIPTION
**Pull request by themylogin**

### CODE REVIEW

**Comment by themylogin** [comment]
time 03:00

**Review by sonicaj — COMMENTED** [review]
We should probably remove all usages of `HAVE_ZPOOL_STATUS_NON_NATIVE_ASHIFT` now as we are assuming that it's going to be there on the zfs versions which `master` is supporting

**Comment by themylogin** [comment]
time 0:30

**Review by sonicaj — APPROVED** [review]
Thanks!

**Pull request merged**
